name: sane
channels:
- conda-forge
dependencies:
- dask=2025.3.0
- duckdb-engine=0.15.0
- duckdb=1.2.1
- eli5=0.13.0
- hvplot=0.11.2
- python-igraph=0.11.8
- imbalanced-learn=0.13.0
- interpret=0.6.10
- ipython=9.1.0
- jupysql=0.11.1
- jupyter=1.1.1
- jupyterlab=4.4.0
- lime=0.2.0.1
- matplotlib=3.10.1
- networkx=3.4.2
- notebook=7.4.0
- numpy=2.2.4
- openpyxl=3.1.5
- optuna=4.2.1
- pandas=2.2.3
- pip=25.0.1
- plotly=6.0.1
- polars=1.27.1
- pyarrow=19.0.1
- pyreadstat=1.2.8
- python=3.12.10
- scikit-learn=1.6.1
- scipy=1.15.2
- seaborn=0.13.2
- shap=0.47.1
- statsmodels=0.14.4
- pip:
  - metasyn==1.1.0
